module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests', '<rootDir>/src'],
  testMatch: [
    '<rootDir>/tests/security/redos-vulnerability-tests.test.ts',
    '<rootDir>/tests/unit/simple.test.ts',
    '<rootDir>/tests/required/payment.service.required.test.ts',
    '<rootDir>/tests/required/auth.middleware.required.test.ts',
    '<rootDir>/tests/required/security.enforcement.required.test.ts',
    '<rootDir>/tests/required/auth.routes.required.test.ts',
    '<rootDir>/tests/required/csrf.mount.required.test.ts',
    '<rootDir>/tests/required/login-csrf-flow.required.test.ts',
    '<rootDir>/tests/unit/services/auth.service.test.ts',
    '<rootDir>/tests/unit/services/rfid.service.test.ts',
    '<rootDir>/tests/unit/services/order.service.test.ts',
    '<rootDir>/tests/unit/services/payment.service.test.ts',
    '<rootDir>/tests/unit/auth.routes.test.ts',
    '<rootDir>/tests/unit/auth.middleware.test.ts',
    '<rootDir>/tests/unit/services/auth.service.coverage.test.ts',
    '<rootDir>/tests/unit/services/order.service.coverage.test.ts',
  ],
  transform: {
    '^.+\\.ts$': ['ts-jest', { useESM: false, isolatedModules: true }],
  },
  setupFiles: ['<rootDir>/tests/setup-env.required.ts'],
  collectCoverageFrom: [
    'src/routes/auth.routes.ts',
    'src/middleware/auth.middleware.ts',
    'src/middleware/csrf.middleware.ts',
    'src/services/payment.service.ts',
    'src/services/auth.service.ts',
    'src/services/rfid.service.ts',
    'src/services/order.service.ts',
    'src/utils/secure-regex.ts',
  ],
  coverageDirectory: 'coverage-required',
  coverageReporters: ['text', 'json', 'lcov'],
  coverageThreshold: {
    global: {
      branches: 16,
      functions: 22,
      lines: 45,
      statements: 45,
    },
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
  },
  testPathIgnorePatterns: [
    '<rootDir>/node_modules/',
    '<rootDir>/dist/',
    '<rootDir>/build/',
    '<rootDir>/web/',
  ],
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],
  testTimeout: 30000,
  clearMocks: true,
  restoreMocks: true,
  maxWorkers: '50%',
};
