 * HASIVU Platform - Global CSS Styles
 * Cross-browser consistent styling with mobile-first responsive design
 * Generated by SuperClaude Wave 3: Frontend Implementation;
import { GlobalStyles as MuiGlobalStyles } from '@mui/material';
import { colors } from './ theme';
// Global CSS styles for consistent cross-browser rendering
export const globalStyles = {}
  // HTML and Body base styles
  html
  body
  // Root element styles
  '#__next': {}
  // Link styles
  a
    '&:focus': {}
      outline: `2px solid ${colors.primary[500]}``
      outline: `2px solid ${colors.primary[500]}``
    border: `1px solid ${colors.neutral[200]}``
    borderBottom: `1px solid ${colors.neutral[200]}``
    borderLeft: `4px solid ${colors.primary[500]}``
    outline: `2px solid ${colors.primary[500]}``
      border: `2px solid ${colors.text.primary}``