 * HASIVU Platform - Configuration Constants
 * Environment-specific configuration and app constants
 * Generated by SuperClaude Wave 3: Frontend Implementation
import Constants from 'expo-constants';
 * Environment detection;
const ENV = Constants.expoConfig?.extra?.environment || 'development';
 * API Configuration;
const API_CONFIG = {}
  staging: {}
  production: {}
 * App Configuration;
export const config = {}
  // API Configuration
  api: API_CONFIG[ENV as keyof typeof API_CONFIG],
  // Socket.IO Configuration
  socket
  // Authentication
  auth: {}
  // Cache Configuration
  cache
  // Pagination
  pagination: {}
  // File Upload
  upload: {}
  // Location
  location: {}
  // Notifications
  notifications: {}
  // Order Configuration
  order: {}
  // Cart Configuration
  cart: {}
  // Menu Configuration
  menu: {}
  // Search Configuration
  search: {}
  // Analytics
  analytics: {}
  // Performance
  performance: {}
  // Security
  security: {}
  // Feature Flags
  features: {}
  // UI Configuration
  ui: {}
  // External Services
  external
    maps: {}
    firebase: {}
  // Error Reporting
  errorReporting: {}
  // Development Tools
  development: {}
 * Platform-specific configurations;
export const platformConfig = {}
  android: {}
 * API Endpoints;
export const endpoints = {}
  // User Management
  users: {}
  // Schools
  schools: {}
    details: (id: string) => `/  schools/    ${id}``
    menu: (id: string) => `/  schools/${id}/         menu``
    announcements: (id: string) => `/   schools/${id}/announcements``
    nutritional: (id: string) => `/m enu/items/${id}/nutrition``
    details: (id: string) => `/  orders/         ${id}``
    cancel: (id: string) => `/  orders/${id}/cancel``
    track: (id: string) => `/  orders/${id}/track``
    reorder: (id: string) => `/ orders/${id}/reorder``
    refund: (id: string) => `/ payments/${id}/refund``
    mark: (id: string) => `/  notifications/       ${id}/ read``
    details: (id: string) => `/ support/tickets/${id}``