# HASIVU Enhanced Prometheus Configuration
# Real-Time System Observability with Multi-Tenant Support
# Supports 500+ schools with complete tenant isolation

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'hasivu-production'
    environment: 'production'
    platform: 'hasivu-multi-school'

# Rule files for advanced alerting
rule_files:
  - '/etc/prometheus/rules/*.yml'
  - '/etc/prometheus/hasivu-rules/*.yml'

# Enhanced alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - hasivu-alertmanager-1:9093
            - hasivu-alertmanager-2:9093
            - hasivu-alertmanager-3:9093
      path_prefix: /alertmanager
      scheme: https
      tls_config:
        ca_file: /etc/ssl/certs/hasivu-ca.crt
        cert_file: /etc/ssl/certs/hasivu-prometheus.crt
        key_file: /etc/ssl/private/hasivu-prometheus.key

# Advanced scrape configurations with multi-tenant support
scrape_configs:
  # ========================================
  # HASIVU CORE PLATFORM MONITORING
  # ========================================

  # Kubernetes API Server monitoring
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - default
            - hasivu-production
            - hasivu-monitoring
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - source_labels:
          [
            __meta_kubernetes_namespace,
            __meta_kubernetes_service_name,
            __meta_kubernetes_endpoint_port_name,
          ]
        action: keep
        regex: default;kubernetes;https
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'apiserver_request_duration_seconds_bucket|apiserver_request_total|apiserver_current_inflight_requests'
        action: keep

  # Kubernetes Node monitoring with resource tracking
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes Pod monitoring with multi-tenant labeling
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - hasivu-production
            - hasivu-analytics
            - hasivu-vendor-marketplace
            - hasivu-monitoring
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name
      # Multi-tenant school identification
      - source_labels: [__meta_kubernetes_pod_label_school_id]
        action: replace
        target_label: school_id
      - source_labels: [__meta_kubernetes_pod_label_tenant_id]
        action: replace
        target_label: tenant_id

  # ========================================
  # HASIVU APPLICATION SERVICES
  # ========================================

  # Kitchen Management System monitoring
  - job_name: 'hasivu-kitchen-management'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [hasivu-production]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: 'hasivu-kitchen-.*'
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: ${1}:8080
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'kitchen_orders_processed_total|kitchen_preparation_time_seconds|kitchen_inventory_items_total|kitchen_staff_efficiency_ratio'
        action: keep

  # Authentication Service monitoring with security metrics
  - job_name: 'hasivu-authentication'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [hasivu-production]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: 'hasivu-auth-.*'
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: ${1}:3001
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'auth_login_attempts_total|auth_successful_logins_total|auth_failed_logins_total|auth_token_validation_duration_seconds|auth_security_events_total'
        action: keep

  # Vendor Marketplace monitoring with AI metrics
  - job_name: 'hasivu-vendor-marketplace'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [hasivu-production]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: 'hasivu-vendor-.*'
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: ${1}:3002
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'vendor_orders_total|vendor_response_time_seconds|vendor_ai_optimization_recommendations_total|vendor_procurement_efficiency_ratio|vendor_supply_chain_reliability_score'
        action: keep

  # Predictive Analytics Engine monitoring
  - job_name: 'hasivu-predictive-analytics'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [hasivu-analytics]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: 'hasivu-analytics-.*'
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: ${1}:5000
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'ml_model_predictions_total|ml_model_accuracy_score|ml_training_duration_seconds|ml_inference_time_milliseconds|analytics_federated_learning_updates_total'
        action: keep

  # Business Intelligence Dashboard monitoring
  - job_name: 'hasivu-business-intelligence'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [hasivu-analytics]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: 'hasivu-bi-.*'
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: ${1}:3000
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'bi_dashboard_views_total|bi_query_execution_time_seconds|bi_data_processing_time_seconds|bi_visualization_render_time_seconds|bi_cross_school_analytics_queries_total'
        action: keep

  # ========================================
  # DATABASE AND STORAGE MONITORING
  # ========================================

  # PostgreSQL multi-tenant database monitoring
  - job_name: 'hasivu-postgresql'
    static_configs:
      - targets:
          - 'hasivu-postgresql-primary:9187'
          - 'hasivu-postgresql-replica-1:9187'
          - 'hasivu-postgresql-replica-2:9187'
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'pg_up|pg_stat_database_tup_inserted|pg_stat_database_tup_updated|pg_stat_database_tup_deleted|pg_stat_database_tup_fetched|pg_locks_count|pg_connections|pg_database_size_bytes|pg_stat_user_tables_n_tup_ins|pg_stat_user_tables_n_tup_upd|pg_stat_user_tables_n_tup_del|pg_stat_replication_lag_seconds'
        action: keep

  # Redis caching layer monitoring
  - job_name: 'hasivu-redis'
    static_configs:
      - targets:
          - 'hasivu-redis-master:9121'
          - 'hasivu-redis-replica-1:9121'
          - 'hasivu-redis-replica-2:9121'
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'redis_up|redis_connected_clients|redis_used_memory_bytes|redis_keyspace_hits_total|redis_keyspace_misses_total|redis_commands_processed_total|redis_memory_usage_ratio|redis_slowlog_length'
        action: keep

  # Object storage monitoring (S3/MinIO)
  - job_name: 'hasivu-object-storage'
    static_configs:
      - targets: ['hasivu-minio:9000']
    metrics_path: /minio/prometheus/metrics
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'minio_cluster_nodes_online_total|minio_http_requests_duration_seconds|minio_network_received_bytes_total|minio_network_sent_bytes_total|minio_s3_requests_total|minio_bucket_usage_total_bytes'
        action: keep

  # ========================================
  # MESSAGE QUEUE AND STREAMING
  # ========================================

  # Apache Kafka monitoring for real-time analytics
  - job_name: 'hasivu-kafka'
    static_configs:
      - targets:
          - 'hasivu-kafka-broker-1:9308'
          - 'hasivu-kafka-broker-2:9308'
          - 'hasivu-kafka-broker-3:9308'
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'kafka_brokers|kafka_topic_partitions|kafka_topic_partition_current_offset|kafka_topic_partition_oldest_offset|kafka_consumer_lag_seconds|kafka_producer_record_send_rate|kafka_consumer_records_consumed_rate'
        action: keep

  # RabbitMQ monitoring for task queuing
  - job_name: 'hasivu-rabbitmq'
    static_configs:
      - targets: ['hasivu-rabbitmq:15692']
    metrics_path: /metrics
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'rabbitmq_up|rabbitmq_connections|rabbitmq_consumers|rabbitmq_queues|rabbitmq_queue_messages|rabbitmq_queue_messages_ready|rabbitmq_queue_messages_unacknowledged|rabbitmq_global_messages_delivered_total'
        action: keep

  # ========================================
  # API GATEWAY AND LOAD BALANCER
  # ========================================

  # NGINX Ingress Controller monitoring
  - job_name: 'hasivu-nginx-ingress'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [nginx-ingress]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
        action: keep
        regex: ingress-nginx
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: ${1}:10254
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'nginx_ingress_controller_requests|nginx_ingress_controller_request_duration_seconds|nginx_ingress_controller_response_size|nginx_ingress_controller_ssl_certificate_info|nginx_ingress_controller_nginx_process_connections'
        action: keep

  # HAProxy load balancer monitoring
  - job_name: 'hasivu-haproxy'
    static_configs:
      - targets: ['hasivu-haproxy:8404']
    metrics_path: /stats/prometheus
    scrape_interval: 30s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'haproxy_server_up|haproxy_server_current_sessions|haproxy_server_response_errors_total|haproxy_server_connection_errors_total|haproxy_backend_response_time_average_seconds|haproxy_backend_current_sessions'
        action: keep

  # ========================================
  # CLOUD PROVIDER INTEGRATION
  # ========================================

  # AWS CloudWatch integration for hybrid monitoring
  - job_name: 'aws-cloudwatch'
    ec2_sd_configs:
      - region: ap-south-1
        port: 9100
        filters:
          - name: tag:Environment
            values: [production]
          - name: tag:Project
            values: [hasivu]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance_name
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [__meta_ec2_availability_zone]
        target_label: availability_zone

  # ========================================
  # CUSTOM BUSINESS METRICS
  # ========================================

  # School-specific metrics collection
  - job_name: 'hasivu-school-metrics'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [hasivu-production]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: 'school-metrics-collector'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'school_active_students_total|school_daily_meals_served_total|school_meal_satisfaction_score|school_inventory_turnover_ratio|school_cost_per_meal_dollars|school_waste_percentage|school_staff_efficiency_score'
        action: keep

  # Financial and billing metrics
  - job_name: 'hasivu-financial-metrics'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [hasivu-production]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: 'financial-metrics-collector'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'billing_monthly_revenue_dollars|billing_cost_per_school_dollars|billing_profit_margin_percentage|payment_transaction_success_rate|payment_processing_time_seconds|financial_compliance_score'
        action: keep

  # ========================================
  # SECURITY AND COMPLIANCE MONITORING
  # ========================================

  # Security events monitoring
  - job_name: 'hasivu-security-monitoring'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [hasivu-security]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: 'security-monitor'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'security_failed_login_attempts_total|security_suspicious_activity_events_total|security_gdpr_compliance_violations_total|security_data_access_requests_total|security_vulnerability_scan_score|security_ssl_certificate_expiry_days'
        action: keep

  # Data privacy compliance monitoring
  - job_name: 'hasivu-privacy-compliance'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: [hasivu-compliance]
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_component]
        action: keep
        regex: 'privacy-monitor'
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'privacy_data_retention_violations_total|privacy_consent_withdrawal_requests_total|privacy_data_anonymization_jobs_total|privacy_cross_border_transfers_total|privacy_audit_trail_completeness_score'
        action: keep

# Storage configuration for high-availability
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 90d
    retention.size: 500GB
    wal-compression: true
    # Enhanced compression for multi-tenant data
    min-block-duration: 2h
    max-block-duration: 25h

# Remote write configuration for long-term storage
remote_write:
  - url: 'https://hasivu-longterm-storage.example.com/api/v1/write'
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
    write_relabel_configs:
      # Only send critical metrics for long-term storage
      - source_labels: [__name__]
        regex: '.*_(total|seconds_sum|seconds_count|bytes|ratio|score)$'
        action: keep

# Remote read configuration for historical data
remote_read:
  - url: 'https://hasivu-longterm-storage.example.com/api/v1/read'
    read_recent: true
    required_matchers:
      environment: production

# Enhanced web configuration for security
web:
  listen-address: '0.0.0.0:9090'
  external-url: 'https://monitoring.hasivu.com/prometheus'
  route-prefix: '/'
  max-connections: 512
  read-timeout: 30s

# Query configuration for performance optimization
query:
  max-concurrency: 20
  timeout: 2m
  max-samples: 50000000
  lookback-delta: 5m
