/**
 * HASIVU Platform - Main Layout Component
 * Provides consistent layout structure for all pages
 * Generated by SuperClaude QA Validation
 */

import React, { ReactNode } from 'react';
import { Box, Container } from '@mui/material';
import Head from 'next/head';

/**
 * Layout Props Interface
 */
export interface LayoutProps {
  /** Child components to render */
  children: ReactNode;
  /** Page title */
  title?: string;
  /** Page description */
  description?: string;
  /** Container variant */
  containerVariant?: 'fixed' | 'fluid';
  /** Show header */
  showHeader?: boolean;
  /** Show footer */
  showFooter?: boolean;
  /** Custom page metadata */
  metadata?: {
    keywords?: string;
    ogImage?: string;
    canonical?: string;
  };
}

/**
 * Header Component
 */
const Header: React.FC = () => {
  return (
    <Box
      component="header"
      sx={{
        bgcolor: 'primary.main',
        color: 'white',
        py: 2,
        borderBottom: '1px solid',
        borderColor: 'divider',
      }}
    >
      <Container maxWidth="lg">
        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            <Box
              sx={{
                fontSize: '1.5rem',
                fontWeight: 'bold',
                fontFamily: 'Poppins, sans-serif',
              }}
            >
              HASIVU
            </Box>
          </Box>
        </Box>
      </Container>
    </Box>
  );
};

/**
 * Footer Component
 */
const Footer: React.FC = () => {
  return (
    <Box
      component="footer"
      sx={{
        bgcolor: 'grey.100',
        borderTop: '1px solid',
        borderColor: 'divider',
        py: 3,
        mt: 'auto',
      }}
    >
      <Container maxWidth="lg">
        <Box sx={{ textAlign: 'center', color: 'text.secondary' }}>
          © {new Date().getFullYear()} HASIVU. All rights reserved.
        </Box>
      </Container>
    </Box>
  );
};

/**
 * Main Layout Component
 */
export const Layout: React.FC<LayoutProps> = ({
  children,
  title = 'HASIVU - Smart School Food Delivery',
  description = 'Revolutionary school food delivery platform with RFID verification and real-time tracking.',
  containerVariant = 'fixed',
  showHeader = true,
  showFooter = true,
  metadata = {},
}) => {
  const {
    keywords = 'school food, delivery, RFID, education, nutrition, parents',
    ogImage = '/images/og-image.jpg',
    canonical,
  } = metadata;

  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta name="keywords" content={keywords} />
        <meta property="og:title" content={title} />
        <meta property="og:description" content={description} />
        <meta property="og:image" content={ogImage} />
        <meta name="twitter:title" content={title} />
        <meta name="twitter:description" content={description} />
        <meta name="twitter:image" content={ogImage} />
        {canonical && <link rel="canonical" href={canonical} />}
      </Head>

      <Box
        sx={{
          display: 'flex',
          flexDirection: 'column',
          minHeight: '100vh',
          bgcolor: 'background.default',
        }}
      >
        {showHeader && <Header />}
        
        <Box component="main" sx={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
          {containerVariant === 'fixed' ? (
            <Container maxWidth="lg" sx={{ py: 3, flex: 1 }}>
              {children}
            </Container>
          ) : (
            <Box sx={{ py: 3, flex: 1 }}>
              {children}
            </Box>
          )}
        </Box>

        {showFooter && <Footer />}
      </Box>
    </>
  );
};

export default Layout;